rl-action-space-shaping-vizdoom-ppo-v3:
    run: PPO
    env: doom
    stop:
        timesteps_total: 2500000
    num_samples: 2
    config:
        lambda: 0.95
        kl_coeff: 0
        clip_rewards: False
        clip_param: 0.2
        vf_clip_param: 0.2
        vf_loss_coeff: 0.5
        grad_clip: 0.5
        entropy_coeff: 0.01
        train_batch_size: 2048
        sample_batch_size: 256
        sgd_minibatch_size: 512
        num_sgd_iter: 4
        num_workers: 1
        num_envs_per_worker: 8
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        vf_share_layers: true
        num_gpus: 1
        lr: 2.5e-4

        env_config:
            env_name:
                grid_search:
                    - ViZDoom-GetToGoal-MultiDiscrete-Strafe-v0
                    - ViZDoom-GetToGoal-Mouse-Minimal-v0
                    - ViZDoom-GetToGoal-Mouse-Backward-v0
                    - ViZDoom-GetToGoal-Mouse-Strafe-v0
                    - ViZDoom-HGS-MultiDiscrete-Strafe-v0
                    - ViZDoom-HGS-Mouse-Minimal-v0
                    - ViZDoom-HGS-Mouse-Backward-v0
                    - ViZDoom-HGS-Mouse-Strafe-v0
                    - ViZDoom-Deathmatch-MultiDiscrete-Strafe-v0
                    - ViZDoom-Deathmatch-Mouse-Minimal-v0
                    - ViZDoom-Deathmatch-Mouse-Backward-v0
                    - ViZDoom-Deathmatch-Mouse-Strafe-v0
            logging_path: "experiments/rllib-vizdoom"

        model:
            custom_model: doom_nature_model